### ISSUE TITLE
Start using precommits 

### ISSUE THREAD

**Issue by gentrexha** [cowprotocol/solver-rewards#115]
I've seen that we often forget running the linting checker/black before doing commits. Maybe a precommit hook might help us for that? I wanna look into setting this up, but I believe it's client side only. What's your opinion on this? 

Reference: https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

**Comment by bh2smith** [comment]
I'm totally cool with this and really like the idea! I have done this in the past for a few projects and have some old hook files lying around we could use. Essentially we would keep a directory in the project called hooks and then instruct the developer to copy that into their .git directory. Then the pre-commit.sh file would execute on commit.

**Comment by gentrexha** [comment]
I think that's a great idea! Please share that!

**Comment by bh2smith** [comment]
We will have to add black and mypy but this old PR should have most of the pieces

https://github.com/gnosis/dex-services/pull/160
