### ISSUE TITLE
Be cautious of Solver Address from Competition Table

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/solver-rewards#232]
We will have to get this from the `tx.from` field of receipt. This field was only recently introduced and whoever backfilled the entries was lazy and put the Zero address everywhere (even though it wold be straight forward to put the real address). We will either need to encourage them to overwrite with correct values or handle it our selves here.

_Originally posted by @bh2smith in https://github.com/cowprotocol/solver-rewards/pull/220#discussion_r1156395391_

**Comment by harisang** [comment]
Not relevant anymore
