### ISSUE TITLE
Respond differently with invalid credentials

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/solver-rewards#239]
Ok, right so one is for fake simulator and the other for a real one. I think the point to be made here is do we really expect the same kind of behaviour in these two different scenarios? Wouldn't we prefer to error if we did not supply the correct credentials?

_Originally posted by @bh2smith in https://github.com/cowprotocol/solver-rewards/pull/231#discussion_r1166769252_

**Comment by harisang** [comment]
Closing as we don't use the concept of internalized transfers anymore
