### ISSUE TITLE
First auction in accounting period not accounted for in Dune query

### ISSUE THREAD

**Issue by fhenneke** [cowprotocol/solver-rewards#264]
There seems to be an off-by-one error in the [solver rewards dune query](https://dune.com/queries/2283297/3741839). The first auction of each accounting period is (sometimes?) not accounted for in the query. This lead to e.g. the [auction with id 6188776](https://api.cow.fi/mainnet/api/v1/solver_competition/6188776) to not be included in the calculation.

`start_block` and `end_block` are computed via
```
block_range as (
    select 
        min("number") as start_block, 
        max("number") as end_block
    from ethereum.blocks 
    where time between cast('{{StartTime}}' as timestamp) and cast('{{EndTime}}' as timestamp)
),
```
and batches are then selected via
```
WHERE block_deadline > (select start_block from block_range)
    AND block_deadline <= (select end_block from block_range)
```
This were correct if the end block of the previous accounting period is the start block of the following accounting period. Then the `WHEN` correctly excludes the start block from the next accounting period.
However, if end block of the previous accounting period is not the start block of the following accounting period differ (because block times do not line with 00:00:00?), the `WHERE` excludes the auction with deadline `start_block` even though it was not accounted for in the previous accounting period.

**Comment by bh2smith** [comment]
So. What date range is in question here? 

Here is the kind of "test query" that would be nice to prepare when creating such an issue

https://dune.com/queries/2432987



Anyway, as far as I can tell this batch would have been accounted for in the previous week. the inequality is `block_deadline > Number` (i.e. strict) and the left bounds are equal.

**Comment by bh2smith** [comment]
I think the `date_trunc` in this might be the solution to this problem:

```sql
where date_trunc('minute', time) 
between cast('{{StartTime}}' as timestamp) and cast('{{EndTime}}' as timestamp)
```
