### ISSUE TITLE
Use more meaningful function name

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/solver-rewards#273]
Nit: Give this function a more meaningful name that describes what it does.

_Originally posted by @gentrexha in https://github.com/cowprotocol/solver-rewards/pull/271#discussion_r1189713941_

**Comment by gentrexha** [comment]
From the [Clean Code Book](https://github.com/jnguyen095/clean-code/blob/master/Clean.Code.A.Handbook.of.Agile.Software.Craftsmanship.pdf):

> Methods should have verb or verb phrase names like postPayment , deletePage , or save.

Therefore, I recommend something along the lines of `preprocessTxHash` or `preptxhash`.

**Comment by harisang** [comment]
Not applicable anymore
