### ISSUE TITLE
Formula for volume based fees might be wrong

### ISSUE THREAD

**Issue by fhenneke** [cowprotocol/solver-rewards#336]
I think the code in this repo (and in dune-sync) for the computation of protocol fees based on volume contains an error.

https://github.com/cowprotocol/solver-rewards/blob/2bda2b1ea0780f8cb66a7be34c41112f0019c9df/queries/orderbook/batch_rewards.sql#L102-L103

The formula is probably correct for buy orders: Suppose the volume without fees is `Y`. Then after adding a fee of `X = 0.0015 * Y` the sell amount is `os.sell_amount = Y + X = (1 + 0.0015) * Y`. From this observable amount we can reconstruct the fee as `X = 0.0015 * Y = 0.0015 / (1 + 0.0015) * os.sell_amount`.

For sell orders the formula is probably incorrect: If the sell amount without fees is `Y` then the fee is `X = 0.0015 Y`. The user still sends `os.sell_amount = Y` for a sell order. Thus the correct fee is reconstucted as `X = 0.0015 * Y = 0.0015 * os.sell_amount`.

Is this how the driver implements volume based fees @sunce86? If so, sell and buy orders could be treated in different cases (using a `CASE` statement) as is done for surplus based fees.

cc @harisang

**Comment by harisang** [comment]
Closing as we don't compute protocol fees any more but fetch them directly from the backend db
