### ISSUE TITLE
ERC20 tokens with ERC721 transfers

### ISSUE THREAD

**Issue by fhenneke** [cowprotocol/solver-rewards#340]
Stange tokens have been traded a few times last accounting period. Those tokens which combine transfers of ERC20 tokens with transfers of ERC721 tokens. It breaks our slippage accounting since it does not emit `Transfer` events (but `ERCTransfer` events?). Those are not handled correctly by our dune slippage query nor by our internalized imbalances code.

[This](https://etherscan.io/tx/0x31b4484fdc55f40ca290cb94a507c96313f93ee3a25834f99b352630814e625c) is an example of a settlement with PANDORA. [This](https://etherscan.io/tx/0x428f77fdbae54b9887901b5c7c778137f26bb2ac508318cf1fd95d824c0d2594) is an example with MNRCH.

An example of a settlement with internalized PANDORA trades is [this](https://etherscan.io/tx/0x35337316dcaafe6e09bda0105ea04c8f9f31c665eedd077a1289ada3d27cfe12).

**Comment by bh2smith** [comment]
Looks like this could be closed since the reference PR has been merged. Note that you can write "closes #X" in the PR description and GitHub will automatically close the issue once merged.

**Comment by fhenneke** [comment]
Closed by #341
