### ISSUE TITLE
New release of eth_typing breaking things

### ISSUE THREAD

**Issue by fhenneke** [cowprotocol/solver-rewards#384]
There has been a [release of eth_typing](https://pypi.org/project/eth-typing/5.0.0/#history) recently which seems to be breaking this repo. The dependency should either be pinned to a previous version or the code should be updated to newer versions of all packages.

**Comment by bh2smith** [comment]
I assume this is related to the failed lint:

https://github.com/cowprotocol/solver-rewards/actions/runs/10403076278/job/28808814628

**Comment by bh2smith** [comment]
I am too lazy to make a fork for this but all you have to do is change this line

https://github.com/cowprotocol/solver-rewards/blob/9c1a602e150fd9061086f79f4315cf1bc3bbf8b2/src/fetch/transfer_file.py#L12

to this

```py
from eth_typing import URI
```

**Comment by bh2smith** [comment]
OH I already have a fork
