### ISSUE TITLE
Notify Solver of Overdraft

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/solver-rewards#85]
Sometimes the solvers slippage penalty exceeds both the gas reimbursement and cow rewards. In which case they owe the protocol an outstanding balance "Overdraft". The rewards accounting should notify the solvers of an amount owed on each payout and provide an address where they can send it.

This could happen automatically (right here within this program). However, if there is a scenario where the proposed transaction is deemed invalid, we wouldn't want to send the notice twice. I would actually propose that this be done manually by on call. Shouldn't be too had to copy and paste some text into telegram.

**Comment by josojo** [comment]
How could the process look like for external solvers? I guess then we need to do things anyways manually, the notification, and receiving of funds...

**Comment by bh2smith** [comment]
The only thing that really makes sense is what we have already discussed in the past. Manually notify the solvers (in telegram) of the amount owed and where to send it. We should probably also record the transaction hash of the payment for our own book keeping.

Closing this issue, since there is nothing to implement here.
